
name: depoly_my_web
 
on:
  workflow_dispatch:
  schedule:
   # 定时执行可参考https://tool.lu/crontab
    - cron: 22 6 */3 * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: 拉取项目
        run: |
          git clone https://gitee.com/newgateway/my.git my
          
      # 配置 git
      - name: config git
        run: git config --global user.email "heytl@qq.com"&&git config --global user.name "heytl"
        
      - name: setup SSH keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.RSA_PRIVATE_KEY }}"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          
      - name: 安装依赖
        # 设置一下 env，就可以使用密钥了
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd my/web/my
          # 初始化 git 项目
          git init
          git add -A
          git commit -m 'message'
          # 推送到指定库
          git push -f git@github.com:heytl/heytl.github.io.git master
        
