# action 的名称
name: depoly_MyUI

# 触发条件：在 push 到 main 分支后
# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:
  schedule:
   # 定时执行可参考https://tool.lu/crontab
    - cron: 22 6 */3 * *
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: heytl/my
          # 放置repository的相对路径
          path: my-ui

      # 生成静态文件
#      - name: Build
#        run: npm install && npm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 打包后的文件部署到哪个分支上
          BRANCH: gh-pages2
          # 打包后的文件在哪里
          FOLDER: my-ui/web/my
          REPOSITORY_NAME: heytl/heytl.github.io

