# action 的名称
name: ssh-agent

# 触发条件
on:
  workflow_dispatch:
  schedule:
   # 定时执行可参考https://tool.lu/crontab
    - cron: 22 6 */3 * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: heytl/my
      - name: Setup key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.RSA_PRIVATE_KEY }}
          
      - name: Deploy
        continue-on-error: false
        run: |
          cd web/my
          git config --global user.email "heytl@qq.com"
          git config --global user.name "heytl!"   
          git init
          git add -A
          git commit -m 'message'
          git push -f git@github.com:heytl/heytl.github.io.git master
         
        
